apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: yingyun-salary-team
  description: The yingyun-salary-team
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: team
  profile:
    displayName: Salary-Team
    email: info@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  