apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lbx-ms-biz-salary-calculator
  description: |
    薪酬执行服务
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: yingyun-team
